### ISSUE TITLE
Question: is zoonavigator's REST API considered public? 

### ISSUE THREAD

**Issue by KazankovMarch** [elkozmon/zoonavigator-api#6]
Is it ok to use this API directly without the zoonavigator-ui? Or it's only for internal usage between these two components and nobody should rely on it?

**Comment by elkozmon** [comment]
TLDR: I'd say go for it! 

Back when I had more time to spend on this project I wanted to refine the API (if needed), add versioning and docs before making it public. If I was to do that now, I would still keep it backwards compatible through versioning, so you would still be safe.
